import Head from 'next/head'
import Image from 'next/image'
import About from './components/About'
import Contact from './components/Contact'
import Main from './components/Main'
import Navbar from './components/Navbar'
import Project from './components/Project'
import Skills from './components/Skills'
export default function Home() {
  return (
    <div className='justify-center'>
     <head>
       <title>Arinze|Full Stack Developer</title>
       <meta name="description" content="generated by next app "/>
       {/* <link rel="icon" href="/favicon.ico"/> */}
     </head>
     <Main/>
     <About/>
     <Skills/>
     <Project/>
     <Contact/>

    </div>
  )
}
